USE [master]
GO

/****** Object:  Database [AgriEnergyUserDB]    Script Date: 5/13/2024 8:38:15 PM ******/
CREATE DATABASE [AgriEnergyUserDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AgriEnergyUserDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AgriEnergyUserDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AgriEnergyUserDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AgriEnergyUserDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AgriEnergyUserDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AgriEnergyUserDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AgriEnergyUserDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AgriEnergyUserDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AgriEnergyUserDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AgriEnergyUserDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [AgriEnergyUserDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET RECOVERY FULL 
GO

ALTER DATABASE [AgriEnergyUserDB] SET  MULTI_USER 
GO

ALTER DATABASE [AgriEnergyUserDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AgriEnergyUserDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AgriEnergyUserDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AgriEnergyUserDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AgriEnergyUserDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AgriEnergyUserDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AgriEnergyUserDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [AgriEnergyUserDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [AgriEnergyUserDB] SET  READ_WRITE 
GO

